#include <iostream>
using namespace std;
int main()
{
 cout << "CHUPALA QUE SABE A MELOCOTÓN DE ALMIBARCHUPALA QUE SABE A MELOCOTÓN DE ALMIBARCHUPALA QUE SABE A MELOCOTÓN DE ALMIBARCHUPALA QUE SABE A MELOCOTÓN DE ALMIBARCHUPALA QUE SABE A MELOCOTÓN DE ALMIBAR";
 return 0;
}
